// <auto-generated />
using System;
using Challengue.Movies.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Challenge.Movies.Persistence.Migrations
{
    [DbContext(typeof(ChallengeDbContext))]
    [Migration("20230412165628_newseeds")]
    partial class newseeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Challenge.Movies.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("35222c2f-f7d3-42e6-9db6-f9aa199bb514"),
                            CreatedBy = "roberto@hireme.com",
                            CreatedDate = new DateTime(2023, 4, 12, 10, 56, 28, 729, DateTimeKind.Local).AddTicks(1519),
                            Name = "Terror"
                        },
                        new
                        {
                            CategoryId = new Guid("99b413d5-626c-46c0-a687-6b1cf12dbcad"),
                            CreatedBy = "roberto@hireme.com",
                            CreatedDate = new DateTime(2023, 4, 12, 10, 56, 28, 729, DateTimeKind.Local).AddTicks(1573),
                            Name = "Comedy"
                        });
                });

            modelBuilder.Entity("Challenge.Movies.Domain.Entities.Movie", b =>
                {
                    b.Property<Guid>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("ImagePoster")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MovieId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = new Guid("70add475-5bfc-499d-817e-90a301378f22"),
                            CategoryId = new Guid("35222c2f-f7d3-42e6-9db6-f9aa199bb514"),
                            CreatedBy = "roberto@hireme.com",
                            CreatedDate = new DateTime(2023, 4, 12, 10, 56, 28, 729, DateTimeKind.Local).AddTicks(1548),
                            Name = "The Basement",
                            ReleaseDate = new DateTime(2023, 4, 12, 10, 56, 28, 729, DateTimeKind.Local).AddTicks(1547),
                            Synopsis = "College students trapped in a haunted house with a living serial killer."
                        },
                        new
                        {
                            MovieId = new Guid("2c3220c4-c111-4701-9d04-394bc4e9a2e8"),
                            CategoryId = new Guid("99b413d5-626c-46c0-a687-6b1cf12dbcad"),
                            CreatedBy = "roberto@hireme.com",
                            CreatedDate = new DateTime(2023, 4, 12, 10, 56, 28, 729, DateTimeKind.Local).AddTicks(1583),
                            Name = "The Wedding Crasher",
                            ReleaseDate = new DateTime(2023, 4, 12, 10, 56, 28, 729, DateTimeKind.Local).AddTicks(1582),
                            Synopsis = "A wedding crasher falls for a crime boss’s daughter and faces hilarious challenges"
                        });
                });

            modelBuilder.Entity("Challenge.Movies.Domain.Entities.Rating", b =>
                {
                    b.Property<Guid>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RateOption")
                        .HasColumnType("int");

                    b.Property<string>("RateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RatingId");

                    b.HasIndex("MovieId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            RatingId = new Guid("b66bdfdb-f178-434e-bbc5-2d1b06d75b5c"),
                            CreatedBy = "roberto@hireme.com",
                            CreatedDate = new DateTime(2023, 4, 12, 10, 56, 28, 729, DateTimeKind.Local).AddTicks(1559),
                            MovieId = new Guid("70add475-5bfc-499d-817e-90a301378f22"),
                            RateOption = 5,
                            RateUser = "roberto@hireme.com"
                        },
                        new
                        {
                            RatingId = new Guid("6566622d-a07c-4307-9d57-7fe4eb1d266f"),
                            CreatedBy = "roberto@hireme.com",
                            CreatedDate = new DateTime(2023, 4, 12, 10, 56, 28, 729, DateTimeKind.Local).AddTicks(1591),
                            MovieId = new Guid("2c3220c4-c111-4701-9d04-394bc4e9a2e8"),
                            RateOption = 5,
                            RateUser = "roberto@hireme.com"
                        });
                });

            modelBuilder.Entity("Challenge.Movies.Domain.Entities.Movie", b =>
                {
                    b.HasOne("Challenge.Movies.Domain.Entities.Category", "Category")
                        .WithMany("Movies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Challenge.Movies.Domain.Entities.Rating", b =>
                {
                    b.HasOne("Challenge.Movies.Domain.Entities.Movie", "Movie")
                        .WithMany("Ratings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Challenge.Movies.Domain.Entities.Category", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("Challenge.Movies.Domain.Entities.Movie", b =>
                {
                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
